[2023-07-25T15:39:06.818-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T13:45:00+00:00 [queued]>
[2023-07-25T15:39:06.825-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T13:45:00+00:00 [queued]>
[2023-07-25T15:39:06.825-0300] {taskinstance.py:1308} INFO - Starting attempt 2 of 5
[2023-07-25T15:39:06.845-0300] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_write_local> on 2023-07-25 13:45:00+00:00
[2023-07-25T15:39:06.849-0300] {standard_task_runner.py:57} INFO - Started process 87825 to run task
[2023-07-25T15:39:06.852-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'LH_ED_GABRIELLEMUNIZ', 'extract_write_local', 'scheduled__2023-07-25T13:45:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/LH_ED_GABRIELLEMUNIZ.py', '--cfg-path', '/tmp/tmp7qps1v10']
[2023-07-25T15:39:06.853-0300] {standard_task_runner.py:85} INFO - Job 180: Subtask extract_write_local
[2023-07-25T15:39:06.906-0300] {task_command.py:410} INFO - Running <TaskInstance: LH_ED_GABRIELLEMUNIZ.extract_write_local scheduled__2023-07-25T13:45:00+00:00 [running]> on host ubuntu
[2023-07-25T15:39:06.999-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabi' AIRFLOW_CTX_DAG_ID='LH_ED_GABRIELLEMUNIZ' AIRFLOW_CTX_TASK_ID='extract_write_local' AIRFLOW_CTX_EXECUTION_DATE='2023-07-25T13:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-25T13:45:00+00:00'
[2023-07-25T15:39:07.008-0300] {logging_mixin.py:150} WARNING - /home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-25T15:39:07.012-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/ind_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 67, in extract_write_local
    extract_write_postgres(date, tables)
  File "/home/gabi/Documentos/Gabi/Indicium/code-challenge-indicium/dags/LH_ED_GABRIELLEMUNIZ.py", line 45, in extract_write_postgres
    for table in tables:
TypeError: 'function' object is not iterable
[2023-07-25T15:39:07.016-0300] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=LH_ED_GABRIELLEMUNIZ, task_id=extract_write_local, execution_date=20230725T134500, start_date=20230725T183906, end_date=20230725T183907
[2023-07-25T15:39:07.033-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 180 for task extract_write_local ('function' object is not iterable; 87825)
[2023-07-25T15:39:07.064-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-25T15:39:07.089-0300] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
